apiVersion: v1
kind: Secret
metadata: 
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
data:
  access_key_id: ${NIFCLOUD_BASE64ENCODE_ACCESS_KEY}
  secret_access_key: ${NIFCLOUD_BASE64ENCODE_SECRET_KEY}
  region: ${NIFCLOUD_REGION}

