---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  name: system:cloud-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: nifcloud-cloud-controller-manager
  name: nifcloud-cloud-controller-manager
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: nifcloud-cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: nifcloud-cloud-controller-manager
    spec:
      serviceAccountName: cloud-controller-manager
      containers:
      - name: nifcloud-cloud-controller-manager
        image: aokumasan/nifcloud-cloud-controller-manager:latest
        imagePullPolicy: Always
        command:
        - /bin/nifcloud-cloud-controller-manager
        - --cloud-provider=nifcloud
        - --leader-elect=true
        - --use-service-account-credentials
        - --allocate-node-cidrs=false
        - --configure-cloud-routes=false
        env:
        - name: NIFCLOUD_REGION
          valueFrom:
            secretKeyRef:
              name: nifcloud-ccm-api-secret
              key: region
        - name: NIFCLOUD_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: nifcloud-ccm-api-secret
              key: access_key_id
        - name: NIFCLOUD_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: nifcloud-ccm-api-secret
              key: secret_access_key
      hostNetwork: true
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

