apiVersion: v1
kind: Secret
metadata:
  name: nifcloud-ccm-api-secret
  namespace: kube-system
type: Opaque
data:
  access_key_id: ${NIFCLOUD_BASE64ENCODE_ACCESS_KEY}
  secret_access_key: ${NIFCLOUD_BASE64ENCODE_SECRET_KEY}
  region: ${NIFCLOUD_REGION}

